name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        
    - name: Build
      run: |
        npm install
        npx webpack
    
    - name: Setup HTML Pages
      uses: actions/configure-pages@v5
  
    - name: Upload HTML artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        name: html
  
    - name: Deploy HTML artifact
      uses: actions/deploy-pages@v4.0.5
